### ISSUE TITLE
Batmode somehow crashes game.

### ISSUE THREAD

**Issue by andesyv** [andesyv/VampireSneaking#28]
While pressing shift it sometimes crashes the game.. Unknown reason.

**Comment by andesyv** [comment]
The issue seems to be an access violation at line 132 in CustomPlayerController.cpp.

**Comment by metrolink** [comment]
The issue is replicable by killing an enemy after a basic attack has been executed on the enemy

**Comment by andesyv** [comment]
Fixed by removing the enemyAI from "Enemies currently targeting player"-array on death.

**Comment by andesyv** [comment]
Please reopen if issue still persist.
